### ISSUE TITLE
Module may cause "Area Code  already set" exception when running other commands

### ISSUE THREAD

**Issue by arion-p** [ashutoshwebkul/magento2-code-generator#42]
With this module installed and enabled, running commands of other modules may result in an exception because the Area Code is set twice.

This is caused by `Webkul\CodeGenerator\Console\Command\Generate` setting the area code in the constructor. 

The constructor is called every time magento is run on the command line, regardless of which command is run. If another command needs to set the area code, it does so in the `execute()` method which is called after all the constructors of all available commands. Since the constructor of `Webkul\...\Command\Generate` already sets the area code, by the time the command is executed, the area code has already been set and the command fails.

For more details see:
https://help.klevu.com/support/solutions/articles/5000871360-area-code-is-already-set
and
https://magento.stackexchange.com/a/332885

**Comment by ghost** [comment]
@arion-p We have fixed this issue in our latest commit as this has been added for custom commands now we have updated the module you can check now. You can take the latest code from the below commit.
https://github.com/webkul/magento2-code-generator/pull/43/commits/bd09067f09d93c5506cb350bdb28af7d2c7e889b
