### ISSUE TITLE
Invalid Param Type of Methods Description

### ISSUE THREAD

**Issue by mahesh-rajawat** [ashutoshwebkul/magento2-code-generator#6]
Ver: 2.0.0

**Actual Result**
1. Tried to generate new model code, its assigning return type as given in `db_schema.xml`.
http://i.prntscr.com/YEgxu4QRQe6FqImAgCgICQ.png 

2. get methods of model and interface must return the valid type, its returning the same class/interface. http://i.prntscr.com/-Qdn3JfHTASQTUVlHdkmOA.png 

**Expected**
it must be as valid return type Like: (int string) etc.
http://i.prntscr.com/HQrXoDBBRkiW0UJ5UYaezQ.png

**Comment by ghost** [comment]
@maheshWebkul721 solution merged thanks
